[project]
name = 'Tokenized-Film-Production-Insurance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.claim-processing]
path = 'contracts/claim-processing.clar'
clarity_version = 2
epoch = 2.5

[contracts.coverage-management]
path = 'contracts/coverage-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-verification]
path = 'contracts/project-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.risk-assessment]
path = 'contracts/risk-assessment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
